### PR TITLE
Updated example to build and run on latest React Native

### PR DESCRIPTION
**Pull request by hsource**
# Summary

While trying to submit a separate PR, I wanted to add something to the test app to allow testing that. I tried a few times, but due to bugs and changes since the version of React Native that was included, I couldn't get it to work.

This fix:

1. Upgrades `react-native` for the example app. It takes as much of the config from a fresh `npx react-native init` project as possible
2. Upgrades dependencies to be compatible with latest react-native
   - Made example app use Podfiles, per new versions
   - Upgraded `flow`, ran `yarn validate:flow`
   - Upgraded `detox`, ran build and test commands; made Android DetoxTest use androidx libraries and upgraded package.json commands
3. Adds new commands to package.json to run the example app, modeled off of `react-native-webview`
   - `yarn start:ios` runs iOS - tested on Simulator
   - `yarn start:android` runs Android - tested on real device

## Tips for reviewers

All manual changes to the React Native boilerplate have comments with "added for" in them, so a quick Ctrl + F wil find most of those.

## Test Plan

Tested by running:
```sh
yarn install
yarn test

yarn start:ios
yarn start:android

# Adjust settings for device in package.json if needed before these blocks
yarn test:detox:android:build:debug
yarn test:detox:android:test:debug
yarn test:detox:android:build:release
yarn test:detox:android:test:release
yarn test:detox:ios:build:debug
yarn test:detox:ios:test:debug
yarn test:detox:ios:build:release
yarn test:detox:ios:test:release
```

### What's required for testing (prerequisites)?

Nothing other than the commands above

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator (no iOS device, only emulator)
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by hsource** [comment]
@bartolkaruza - you seem to be the main maintainer! Thanks a lot for your work on this repo. Take a look and see if this might be something you're interested in merging.

**Comment by hsource** [comment]
@bartolkaruza - thanks for maintaing this package! Can you take a look at this change? It's very helpful to submit this before #178

**Comment by bartolkaruza** [comment]
@hsource thank you for this, awesome contribution (from maintainer point of view :))! I've updated the circleci build orb on master, which should solve the build issue on this PR. Could you try rebasing on master to see if that worked?

**Comment by hsource** [comment]
It wasn't passing due to a missing set of setup lines required for the circleci orb. I added them to android/app/build.gradle and it works now

**Comment by bartolkaruza** [comment]
@hsource Perfect, thank you!

**Pull request merged**
