### PR TITLE
Improve get photos logic per Jared Sumner's solution

### PR DESCRIPTION
**Pull request by guy-shahine**
# Summary

We're facing slow performance speed when loading photos. Jared Sumner provided a solution that's explained in more details in #138 and other related issues are #110 and #168 

NOTE: CameraRollExample doesn't work in Xcode 11+ because it requires an upgrade of React Native.

## Test Plan

Since it's an improvement, I ran the existing tests and got no failures.

### What's required for testing (prerequisites)?

1. Run CameraRollExample project
2. Accept access to photo albums
3. Observe the images load speed

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    N/A     |

## Checklist

- [X] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by pribeh** [comment]
Quadruple pump this.

**Comment by gordonwhitehouse** [comment]
Yes please. I quintuple pump this

**Comment by pribeh** [comment]
@guy-shahine why did you close the pr?

**Comment by guy-shahine** [comment]
@pribeh multiple reasons:
a) The package is still wired with an old structure and versions that prevents it from compiling with latest xcode
b) The tests passed but then I discovered a bug in Jared's code where a variable name was missing so tests are unreliable
c) I managed to get the example project to run in simulator but can't run on device (it requires an older iOS version that I don't have available)
d) No feedback, follow up or engagement from the maintainers

**Comment by pribeh** [comment]
@guy-shahine thanks for sharing and your effort to implement this – I understand

**Comment by tvpranav** [comment]
@guy-shahine Have we got any solution for thumbnail of images to make it more faster?

**Comment by guy-shahine** [comment]
We couldn't solve it using this library so we changed our logic to use a different library that invokes the native photo picker.

**Comment by aldimirprincipal** [comment]
> @tvpranav We couldn't solve it using this library so we changed our logic to use a different library that invokes the native photo picker.

Could you please tell me the library you are using? We are trying to implement a gallery but it's impossible on iOS since the memory leak and the slow performance

**Pull request closed without merging**
