### PR TITLE
Get album list

### PR DESCRIPTION
**Pull request by r0b0t3d**
# Summary

This PR add support to get album list

## Test Plan

Local test on real devices and simulators

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [x] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by jayeshghyperlink** [comment]
hello @bartolkaruza  may i know when new version of this library is going to release with getAlbumList change?

**Comment by yildirayunlu** [comment]
@bartolkaruza waiting getAlbums release.

**Comment by bartolkaruza** [comment]
go for 1.5.1 instead of 1.5.0

**Comment by dokkis** [comment]
@r0b0t3d this commit contains an exception swallow that doesn't reject the promise here: https://github.com/react-native-community/react-native-cameraroll/blob/master/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java#L430

I was calling the function and it wasn't either going into the `then` or `catch` part of the promise. That's why, I am still trying to figure it out what is the issue and why go in Exception (testing on Android API Level 29 for now).

**Comment by r0b0t3d** [comment]
@dokkis Good catch! Can you open new issue? This one already merged.

**Comment by dokkis** [comment]
@r0b0t3d yep, I was going to do that, opened here: https://github.com/react-native-community/react-native-cameraroll/issues/174

**Pull request merged**
