### PR TITLE
Support filter media items between dates

### PR DESCRIPTION
**Pull request by r0b0t3d**
# Summary
This PR is a replacement of #120 that I closed accidentally. So I am going to copy the description below.

Add `fromTime` and `toTime` to `getPhotos` to get media items in between

## Test Plan
Manual test on my device

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅    |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [x] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by bartolkaruza** [comment]
looks good, thanks!

**Comment by imranmirza-nxb** [comment]
@bartolkaruza I'm using 1.4.1 also tried 1.4.0, Without time filter system fetch all the photos from the camerarole that I have added few minutes/hours back, but unable to get any photo if I add 'fromTime' and 'toTime'.

Can you please confirm if this issue is fixed in this PR?

`CameraRoll.getPhotos({
        first: 20,
        assetType: 'Photos',
        fromTime: 1584356434595, //5 hours back
        toTime: moment().valueOf(),
      })`

**Comment by r0b0t3d** [comment]
@imranmirza-nxb I tried your code above, works well for me on both android and ios
```
CameraRoll.getPhotos({
  first: 20,
  assetType: 'Photos',
  fromTime: 1584356434595, //5 hours back
  toTime: moment().valueOf(),
})
```

**Comment by imranmirza-nxb** [comment]
@r0b0t3d in my case getPhotos without time filter returns me 'timestamp = 0' not sure why, this might be an issue, is there anything required to save timestamp while storing in camerarole ?

`const data = await this.camera.takePictureAsync({quality: 0.5, base64: true});
CameraRoll.saveToCameraRoll(data.uri)`

`{"node": {"group_name": "Pictures", "image": [Object], "timestamp": 0, "type": "image/jpeg"}}`

**Comment by r0b0t3d** [comment]
I haven't got the problem with `timestamp` while saving so far. Did it happen on ios/android or both?
If you find that this is really a bug, you could open another issue to keep track.

**Comment by imranmirza-nxb** [comment]
Thanks for quick response. I'm testing so far over Android Simulator.

My getPhotos returns me following object with timestamp=0: 
`{"node": {"group_name": "Pictures", "image": [Object], "timestamp": 0, "type": "image/jpeg"}}`.

Can you please confirm two things for your case:
1. While saveToCameraRoll you didn't give explicitly any timestamp param and system save photo automatically with some creation time.
2. Your getPhotos returned e.edges object contains some value in the "timestamp" and its not "0" as in my case its 0?

**Comment by r0b0t3d** [comment]
@imranmirza-nxb just tried with emulator (android 10), got the same problem as yours. It seems something went wrong with emulator or android 10 (not sure about it).
You can try with real device to see whether it works or not.

**Comment by imranmirza-nxb** [comment]
Yes, On real device this is working fine, the module has issue with emulator only. 
Thank you for your cooperation @r0b0t3d.

**Comment by tauqeer81** [comment]
On **Android SDK 29** `CameraRoll.getPhotos({ first: 20, assetType: 'Photos', fromTime: 1584356434595, //5 hours back toTime: moment().valueOf(), })` returns empty `edges`. However it works perfect on **Android SDK 28**. How to resolve that issue?

**Pull request merged**
