### PR TITLE
Remove unnecessary publish job requirement

### PR DESCRIPTION
**Pull request by cesargdm**
# Summary

Cleanup of the CircleCI workflow, there's no need to make publish job dependant of analyze, since analyze is already dependent on checkout_code

Screen Shot 2020-06-30 at 1 21 46 PM

New pipeline:
Screen Shot 2020-06-30 at 1 25 28 PM

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by cesargdm** [comment]
Actually, does publish would need android_* jobs to be completed before?

**Comment by bartolkaruza** [comment]
> there's no need to make publish job dependant of analyze
Did you mean `there is no need to make publish depend on checkout_code`?

**Comment by bartolkaruza** [comment]
> Actually, does `publish` would need `android_*` jobs to be completed before?

It would be an improvement. The current setup is left over from when the android builds were very unreliable. Right now, they are passing consistently already for a long time, so we could make them required to pass before publishing.

**Pull request merged**
