### PR TITLE
Fixed 'Invalid column longitude' in Android 29 SDK 

### PR DESCRIPTION
**Pull request by slavakoshevoi**
The error is still reproducing for image location on API 29
I added checking for android API. Set LONGITUDE and LATITUDE for images if API < 29

This is an error screenshot:
Screenshot_2020-05-06 20-28-24

### CODE REVIEW

**Comment by syedrahaman92** [comment]
Looks good to me

**Comment by syedrahaman92** [comment]
@bartolkaruza anything else is needed to merge this PR?

**Comment by dokkis** [comment]
@slavakoshevoi given that in this PR https://github.com/react-native-community/react-native-cameraroll/pull/114 we're not using latitude and longitude anymore to fetch those information but we use `ExifInterface#getLatLong`, should we simply remove them from PROJECTION list as opposed to have a conditional with API Level? @syedrahaman92 thoughts?

**Comment by syedrahaman92** [comment]
@dokkis @slavakoshevoi I also think we don't need Images.Media.LONGITUDE and Images.Media.LATITUDE anymore. Below API Level 29, it will also work because `ExifInterface#getLatLong` is introduced in API Level 5 https://developer.android.com/reference/android/media/ExifInterface#getLatLong(float%5B%5D)

**Comment by slavakoshevoi** [comment]
@syedrahaman92 @dokkis Agree with you guys. I've updated code

**Comment by syedrahaman92** [comment]
LGTM

**Comment by slavakoshevoi** [comment]
@bartolkaruza can we merge this fix?

**Comment by 2IhsanWp** [comment]
I still face this issue even after update to lates cameraroll version and update sdktarget 29

**Comment by 2IhsanWp** [comment]
I still face this issue even after update to lates cameraroll 4.0.0 and targetSDK 29

**Comment by hiroyaiizuka** [comment]
me too, still error happens... with cameraroll 4.0.1 amd targetSDK 29

**Pull request merged**
