### PR TITLE
Default groupTypes to "All"

### LINKED ISSUE #18: Camera Roll not returning any photos on iOS
I reported this bug in the react-native repo here at [facebook/react-native#24140](https://github.com/facebook/react-native/issues/24140) , but they said to post it here.

## 🐛 Bug Report
When fetching photos from the Camera Roll on **iOS** by calling `CameraRoll.getPhotos()`, it always return an empty array of edges in the data. This problem is not present when I run it on Android nor in a Snack. I tried implementing the [community version](https://github.com/react-native-community/react-native-cameraroll) and the [built-in version](https://facebook.github.io/react-native/docs/cameraroll) of the Camera Roll, but the problem persisted. I also tried running it on the iOS simulator, on an iPhone, and an iPad with no success.

## To Reproduce

1. Create a new react native project (with `react-native init`)
2.  Link the Camera Roll library
  a. With the RCTCameraRoll library as described [here](https://facebook.github.io/react-native/docs/cameraroll) from facebook's website
  b. Or with the RNCCameraRoll library as described in your README
3. Add the permission keys in the Info.plist as described [here](https://facebook.github.io/react-native/docs/cameraroll#permissions) from facebook's website
4. Copy paste the [sample code](https://facebook.github.io/react-native/docs/cameraroll#example) from facebook's website
5. Run `react-native start --reset-cache` (Solved the problems I was having with metro)
5. Run `react-native run-ios`

## Expected Behavior

I would expect the Camera Roll getPhotos function to return a populated edges array in the edges with the information/URI of images in the phones camera roll.

## Code Example

Cannot replicate bug in a [Snack](https://snack.expo.io/@benjeau/react-native-camera-roll-ios-issue).

**With the built-in Camera Roll**
Here is a [repo](https://github.com/BenJeau/reactNativeCameraRollIssue/tree/1919797c473e93c37f56ee1af79ca52dc361553d) with the code example. I also uploaded the iOS release app file to [appetize.io](https://appetize.io/app/xcva0fr6xhqtyt1yvt1jywy61g), which does have the problem. 

**With the community version**
Here is a [repo](https://github.com/BenJeau/reactNativeCameraRollIssue/tree/a54275c2283e627dd83d94c338a621349e8cb311) with the code example. I also uploaded the iOS release app file to [appetize.io](https://appetize.io/app/z6je8vmbc6um2d7cd5y46wd188), which does have the same problem.

## Environment
Output of the `react-native info` command

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 18.59 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 21, 23, 25, 26, 27, 28
        Build Tools: 21.1.2, 23.0.3, 25.0.2, 26.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

### LINKED ISSUE #23: Fails to build/install/test on XCode 10.2
When using XCode 10.2 project cannot be built or tested due to a bug in Detox which fails to build Detox itself. Attempting to do so will generate the error:
```
(...) could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
```
and
```
Error: Command failed: (...)/node_modules/detox/scripts/build_framework.ios.sh (...)
```

A fix was released 6 days ago:
https://github.com/wix/Detox/issues/1229

The upcoming PR for #18 will also fix this issue. This issue is created  for any lost souls that may be googling for an answer.

### PR DESCRIPTION
**Pull request by scarlac**
Fixes #18 (Fails to build/install/test on XCode 10.2)
Fixes #23 (Camera Roll not returning any photos on iOS)

### CODE REVIEW

**Comment by JoshuaGross** [comment]
This looks reasonable to me. If Android and iOS are now both returning sensible photos for the first page of results, I'm fine with it.

**Comment by scarlac** [comment]
How do you normally test it? I ran it against my own project, but is there an automated test somewhere (that isn't just snapshots)?

**Comment by bartolkaruza** [comment]
> How do you normally test it? I ran it against my own project, but is there an automated test somewhere (that isn't just snapshots)?

There is a basic setup for Detox tests to run CI, but I've had trouble getting them to work since the start of this repo. After they are working, the plan is to expand the number of e2e tests to include basic cases. We could really use help in this area and other maintenance of this repo. 

Thanks for this PR @scarlac , I'll get it merged as soon as CI is working again, so that it makes it into the very next release (using semantic-release).

**Comment by bartolkaruza** [comment]
@scarlac can you rebase your branch on Master dropping your package.json and yarn.lock changes? I've updated all dependencies in [another PR](https://github.com/react-native-community/react-native-cameraroll/pull/31), which has a dependency update for all dependencies and is already merged.

**Comment by scarlac** [comment]
@bartolkaruza Sure thing. You still have the <0.59 requirement in package.json which doesn't include 0.59 itself? I'll leave those changes out though. Just an FYI.

**Comment by scarlac** [comment]
@bartolkaruza PR is ready for your review, so whenever you have time :)

**Comment by bartolkaruza** [comment]
Thanks @scarlac this lgtm!
> You still have the <0.59 peer depdendency requirement in package.json
I'll update it

**Pull request merged**
